spring.application.name=hirehelper
spring.datasource.url=jdbc:mysql://localhost:3306/MySQL_DATABASE_NAME;

spring.datasource.username=MySQL_USER_NAME;
spring.datasource.password=Thameem@836

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MySuperSecretKeyForHireHelperProject2026
jwt.expiration=86400000
